name: Check Outdated Dependencies

on:
  schedule:
    # Run the workflow every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"

    - name: Check outdated dependencies
      run: pip list --outdated --format=json > outdated.json || true

    - name: Make createDependencyBranches.sh executable
      run: chmod +x createDependencyBranches.sh

    - name: Create branches for outdated dependencies
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        if [ -s outdated.json ]; then
          ./createDependencyBranches.sh
          echo "HAS_OUTDATED_DEPENDENCIES=true" >> $GITHUB_ENV
        else
          echo "HAS_OUTDATED_DEPENDENCIES=false" >> $GITHUB_ENV
        fi

    - name: Trigger PR creation workflow
      if: env.HAS_OUTDATED_DEPENDENCIES == 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: outdated-dependencies
        client-payload: '{"has_outdated_dependencies": "true"}'